version: '3.8'

services:
  client:
    build: ./client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  server:
    build: ./server
    ports:
      - '5001:5001'
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb+srv://intern:QOkUN3sgS8kjbZcj@multitubesproductionclu.9qgtt.mongodb.net/?retryWrites=true&w=majority&appName=MultitubesProductionCluster
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongo-data:
