version: '3.8'

services:
  client:
    build: ./client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  server:
    build: ./server
    ports:
      - '5001:5001'
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - variables.env

